# -*- coding: utf-8 -*-
"""Day1MiniProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RNA4wyHlYnPatPOhVRErZVRgNiOEF2gm
"""

print("=" * 50)
print("        STUDENT DATA EXPLORER PROJECT")
print("=" * 50)

import pandas as pd

# Load CSV file
df = pd.read_csv('/content/student_performance.csv')

print("="*40)
print("STUDENT DATA EXPLORER")
print("="*40)

print("\nDATASET OVERVIEW")
print("-" * 30)

print(f"Total number of students: {len(df)}")
print(f"Total number of columns: {len(df.columns)}")
print(f"Unique departments: {df['department'].nunique()}")

print("\nDEPARTMENT WISE ANALYSIS")
print("-" * 30)

dept_count = df['department'].value_counts()

print(dept_count)

print("\nSCORE ANALYSIS")
print("-" * 30)

print(f"Highest Math Score: {df['math_score'].max()}")
print(f"Lowest Math Score: {df['math_score'].min()}")
print(f"Average Math Score: {df['math_score'].mean():.2f}")

print(f"Average Programming Score: {df['programming_score'].mean():.2f}")

print(f"Average Attendance: {df['attendance_percentage'].mean():.2f}%")

print(df.columns)

df['total_score'] = (
    df['math_score']
    + df['programming_score']
)

print(df.isnull().sum())

print("\nGENDER WISE ANALYSIS")
print("-" * 30)

gender_avg = df.groupby(
    'gender'
)['total_score'].mean()

print(gender_avg)

print("\nTOP 5 PERFORMERS")
print("-" * 30)

top5 = df.sort_values(
    by='total_score',
    ascending=False
).head(5)

print(
    top5[
        ['name',
         'department',
         'total_score']
    ]
)

print("\nATTENDANCE ANALYSIS")
print("-" * 30)

low_attendance = df[
    df['attendance_percentage'] < 75
]

if len(low_attendance) > 0:
    print(
        low_attendance[
            ['name',
             'department',
             'attendance_percentage']
        ]
    )
else:
    print(
        "All students have attendance above 75%"
    )

electronics = len(
    df[
        df['department'] == 'Electronics'
    ]
)

print(electronics)

female_avg = df[
    df['gender'] == 'Female'
]['attendance_percentage'].mean()

print(female_avg)

lowest = df.loc[
    df['programming_score'].idxmin()
]

print(lowest['name'])

count = len(
    df[
        df['math_score'] > 80
    ]
)

print(count)

avg_total = df[
    df['attendance_percentage'] > 90
]['total_score'].mean()

print(avg_total)