# -*- coding: utf-8 -*-
"""Phase1_Capstone_Project.ipynbipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nzNfz2ZrHT8wbp3oElcOUEqma5DLRbYE
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_excel("Telco_customer_churn.xlsx")

df.head()

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Records:")
print(df.duplicated().sum())

"""# Data Ingestion Using Pandas

The dataset was loaded into a Pandas DataFrame and analyzed for:
- Shape
- Columns
- Data Types
- Missing Values
- Duplicate Records
"""

# Check shape before cleaning
print("Before Cleaning:", df.shape)

# Remove duplicates
df = df.drop_duplicates()

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Save cleaned dataset
df.to_csv("cleaned_telco_churn.csv", index=False)

print("\nCleaned dataset saved successfully!")
print("After Cleaning:", df.shape)

df.shape

df.isnull().sum()

# Fill missing Churn Reason values

df["Churn Reason"] = df["Churn Reason"].fillna("No Churn")

# Verify
print(df["Churn Reason"].isnull().sum())

df.to_csv("cleaned_telco_churn.csv", index=False)

print("Cleaned dataset saved successfully!")

"""# Data Cleaning and Preprocessing

The dataset was examined for missing values and duplicate records.

Findings:
- No duplicate records were found.
- The column 'Churn Reason' contained 5174 missing values.
- Missing values were replaced with 'No Churn'.
- The cleaned dataset was saved as a new CSV file.
"""

import sqlite3

conn = sqlite3.connect("telco_churn.db")

df.to_sql(
    "customers",
    conn,
    if_exists="replace",
    index=False
)

print("Data inserted successfully!")

query = "SELECT COUNT(*) AS total_records FROM customers"

pd.read_sql(query, conn)

"""# SQL Analysis

The following SQL queries demonstrate:
- Filtering
- Sorting
- Aggregation
- Group By
- Conditional Queries
"""

q1 = """
SELECT CustomerID,
       Gender,
       [Monthly Charges]
FROM customers
WHERE [Monthly Charges] > 80
LIMIT 10
"""

pd.read_sql(q1, conn)

q2 = """
SELECT CustomerID,
       [Monthly Charges]
FROM customers
ORDER BY [Monthly Charges] DESC
LIMIT 10
"""

pd.read_sql(q2, conn)

q3 = """
SELECT
AVG([Monthly Charges]) AS Average_Monthly_Charge,
MAX([Monthly Charges]) AS Maximum_Charge,
MIN([Monthly Charges]) AS Minimum_Charge
FROM customers
"""

pd.read_sql(q3, conn)

q4 = """
SELECT Gender,
COUNT(*) AS Total_Customers
FROM customers
GROUP BY Gender
"""

pd.read_sql(q4, conn)

q5 = """
SELECT CustomerID,
       Gender,
       [Tenure Months]
FROM customers
WHERE [Tenure Months] > 24
AND [Churn Label] = 'Yes'
LIMIT 10
"""

pd.read_sql(q5, conn)

query = """
SELECT *,

CASE
WHEN [Monthly Charges] >= 70
THEN 'High Spending'
ELSE 'Low Spending'
END AS Spending_Category,

CASE
WHEN [Tenure Months] >= 24
THEN 'Loyal Customer'
ELSE 'New Customer'
END AS Customer_Status

FROM customers
"""

transformed_df = pd.read_sql(query, conn)

transformed_df.head()

transformed_df.to_csv(
    "transformed_telco_churn.csv",
    index=False
)

print("Transformed dataset exported successfully!")

"""# ETL Pipeline

ETL stands for Extract, Transform, and Load.

Extract:
- Read data from source files.

Transform:
- Clean and prepare the data.

Load:
- Save the processed data for further analysis.
"""

import pandas as pd

# Extract
def extract():
    print("Extracting data...")
    return pd.read_csv("cleaned_telco_churn.csv")

# Transform
def transform(df):
    print("Transforming data...")

    df["Customer_Status"] = df["Tenure Months"].apply(
        lambda x: "Loyal" if x >= 24 else "New"
    )

    return df

# Load
def load(df):
    print("Loading data...")

    df.to_csv(
        "etl_output.csv",
        index=False
    )

# Execute ETL

data = extract()

data = transform(data)

load(data)

print("ETL Pipeline Completed Successfully!")

!pip install pyspark

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("CapstoneProject") \
    .getOrCreate()

spark_df = spark.read.csv(
    "cleaned_telco_churn.csv",
    header=True,
    inferSchema=True
)

spark_df.show(5)

spark_df.write.mode("overwrite").parquet("bronze_layer")

print("Bronze Layer Created")

silver_df = spark_df.dropDuplicates()

silver_df = silver_df.na.drop()

silver_df.write.mode("overwrite").parquet("silver_layer")

print("Silver Layer Created")

from pyspark.sql.functions import avg

gold_df = silver_df.groupBy(
    "Gender"
).agg(
    avg("Monthly Charges").alias("Avg_Monthly_Charges")
)

gold_df.show()

gold_df.write.mode("overwrite").parquet("gold_layer")

print("Gold Layer Created")

"""# CSV vs Parquet Comparison

| Feature | CSV | Parquet |
|----------|----------|----------|
| File Size | Larger | Smaller |
| Storage Efficiency | Low | High |
| Read Speed | Slower | Faster |
| Write Speed | Moderate | Faster for Analytics |
| Compression | No | Yes |
| Human Readable | Yes | No |
| Best Use Case | Data Exchange | Big Data Analytics |
| Limitation | Large Storage | Not Human Readable |

Observation:
Parquet is more efficient for big data processing and analytics because it supports compression and columnar storage.
"""

gold_parquet = spark.read.parquet(
    "gold_layer"
)

gold_parquet.show()

gold_pd = gold_parquet.toPandas()

gold_pd.head()

"""# Parquet to Pandas Conversion

The Gold Layer Parquet file was successfully read using PySpark and converted back into a Pandas DataFrame for further analysis.
"""

import matplotlib.pyplot as plt

df["Gender"].value_counts().plot(
    kind="bar"
)

plt.title("Gender Distribution")
plt.xlabel("Gender")
plt.ylabel("Count")

plt.show()

df["Churn Label"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%"
)

plt.ylabel("")

plt.title("Customer Churn Distribution")

plt.show()

df["Monthly Charges"].plot(
    kind="hist",
    bins=20
)

plt.title("Monthly Charges Distribution")

plt.xlabel("Monthly Charges")

plt.show()

from sklearn.preprocessing import LabelEncoder

df_ml = df.copy()

for col in df_ml.select_dtypes(include="object").columns:
    df_ml[col] = LabelEncoder().fit_transform(
        df_ml[col].astype(str)
    )

from sklearn.model_selection import train_test_split

X = df_ml.drop(
    "Churn Value",
    axis=1
)

y = df_ml["Churn Value"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    random_state=42
)

model.fit(
    X_train,
    y_train
)

from sklearn.metrics import accuracy_score

pred = model.predict(X_test)

print(
    "Accuracy:",
    accuracy_score(y_test, pred)
)

"""# Conclusion

This project successfully demonstrated:

- Data Ingestion using Pandas
- Data Cleaning and Preprocessing
- SQLite Database Integration
- SQL Analysis
- SQL-Based Transformation
- ETL Pipeline
- PySpark Medallion Architecture
- CSV vs Parquet Comparison
- Parquet to Pandas Conversion
- Data Visualization
- Machine Learning Model Training and Evaluation

The project showcased an end-to-end Data Engineering workflow from raw data ingestion to business-ready analytics and predictive modeling.
"""

